name: Replace-With-Your-Action-Name
description: Replace-With-Your-Action-Description
inputs:
 path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: Dockerfile
 image_name:
    description: "Name of the docker image"
    required: true
 tag_name:
    description: "Tag name for docker image"
    required: false
runs:
  using: composite
  steps:
    - name: Create DockerImage
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
            export TAG=$(date +%s)
        else
            export TAG="${{ inputs.tag_name }}"
        fi
        docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ inputs.image_name }}:$TAG
        docker image ls
      shell: bash