name: Replace-With-Your-Action-Name
description: Replace-With-Your-Action-Description
runs:
  using: composite
  steps:
    - run: |
        echo "Building"
      shell: bash
    - name: Build with Maven
      run: mvn -B package --file pom.xml