name: Docker push
description: "Docker push "
inputs:
  docker_hub_username:
    description: "docker hub username"
    required: true
  docker_image:
    description: "Docker image"
    required: true
runs:
  using: composite
  steps:
    - run: |
        docker tag "${{ inputs.docker_image }}" "${{inputs.docker_hub_username}}/${{inputs.docker_image}}"
        docker push "${{ inputs.docker_hub_username}}/${{inputs.docker_image}}"
      shell: bash